def get_news_data():
    """
    Sumber data utama untuk berita. Setiap item berisi konten lengkap.
    """
    news_items = [
        {
            "id": 1,
            "title": "Harga Tomat Turun, BPS Catat Indonesia Alami Deflasi pada Agustus 2025",
            "description": "BPS mencatat tomat menyumbang deflasi pada Agustus 2025.",
            "url": "https://ekonomi.republika.co.id/berita/t1wblz490/harga-tomat-turun-bps-catat-indonesia-alami-deflasi-pada-agustus-2025",
            "imageUrl": "https://cdn.pixabay.com/photo/2016/12/06/18/27/tomatoes-1887240_1280.jpg",
            "publishedAt": "2025-09-01T13:05:00Z",
            "source": "Republika",
            "content": "Badan Pusat Statistik (BPS) mencatat terjadi deflasi sebesar 0,08 persen secara bulanan pada Agustus 2025. Salah satu kontributor utama penurunan indeks harga konsumen adalah komoditas tomat, yang memberi andil deflasi sebesar 0,01 persen. Meskipun secara tahunan masih terdapat inflasi sebesar 2,31 persen, penurunan harga tomat menjadi penyangga deflasi pada bulan tersebut. Artinya, komoditas ini memiliki pengaruh nyata terhadap stabilitas harga pangan nasional. ",
            "category": "Ekonomi & Inflasi",
        },
        {
            "id": 2,
            "title": "Harga Tomat Anjlok? Jangan Panik, Saatnya Petani dan Pelaku Usaha Berinovasi!",
            "description": "Petani didorong olah tomat jadi produk bernilai saat harga anjlok.",
            "url": "https://unej.ac.id/blog/2025/08/29/harga-tomat-anjlok-jangan-panik-saatnya-petani-dan-pelaku-usaha-berinovasi/",
            "imageUrl": "https://cdn.pixabay.com/photo/2016/12/27/21/22/salad-1934944_1280.jpg",
            "publishedAt": "2025-08-29T00:00:00Z",
            "source": "Universitas Jember (UNEJ)",
            "content": "Dr. Nurhayati dari Universitas Jember menyatakan bahwa ketika harga tomat turun tajam akibat overproduksi, inovasi menjadi solusi utama agar tomat tidak cepat rusak dan memiliki nilai tambah. Ia menyarankan pengolahan menjadi produk seperti pasta, saus, jus, selai, tomat kering, hingga teknik modern seperti bubuk (spray drying), freeze drying, atau fermentasi (anggur/cuka tomat). Ekstraksi likopen, pengolahan kulit/ biji menjadi kosmetik atau pewarna alami, bahkan paten produk makin perlu dikembangkan. Inovasi ini membuka peluang bagi UMKM dan perlindungan ekonomi bagi petani. ",
            "category": "Inovasi & Olahan",
        },
        {
            "id": 3,
            "title": "Harga Tomat di Talaud Naik hingga Rp15 Ribu per Kg",
            "description": "Harga tomat di Talaud naik tajam jadi Rp15.000/kg.",
            "url": "https://rri.co.id/daerah/1786243/harga-tomat-di-talaud-naik",
            "imageUrl": "https://cdn.pixabay.com/photo/2018/05/09/21/42/vegetables-3386212_1280.jpg",
            "publishedAt": "2025-08-22T00:00:00Z",
            "source": "RRI",
            "content": "Harga tomat di Kabupaten Talaud dilaporkan naik tajam dari sekitar Rp10.000 per kilogram menjadi Rp15.000 per kilogram. Kenaikan ini terjadi dalam waktu singkat dan membuat pedagang serta konsumen merasakan tekanan harga. Kenaikan diduga disebabkan oleh gangguan pasokan dan cuaca yang ekstrem, memengaruhi distribusi hasil panen dari daerah penghasil. ",
            "category": "Pasar & Harga",
        },
        {
            "id": 4,
            "title": "Petani Tomat di Ngasem Tingkatkan Hasil Panen dengan Pupuk Agensi Hayati",
            "description": "Pupuk semi-organik menggandakan produksi tomat di Ngasem.",
            "url": "https://arahjatim.com/petani-tomat-di-ngasem-inovasi-pupuk-agensi-hayati-hasil-panen-naik-dua-kali-lipat/",
            "imageUrl": "https://cdn.pixabay.com/photo/2017/07/19/08/50/gardening-2518377_1280.jpg",
            "publishedAt": "2025-08-14T00:00:00Z",
            "source": "Arah Jatim",
            "content": "Di Ngasem, petani tomat berhasil menggandakan hasil panen mereka setelah menerapkan pupuk agensi hayati—kombinasi pupuk organik cair dan pupuk kimia. Dengan metode semi-organik ini, hasil panen meningkat hingga dua kali lipat dibanding sebelumnya. Petani melaporkan bahwa tanaman lebih sehat, akar lebih kuat, dan buah matang merata. Inovasi ini menawarkan pendekatan budidaya yang lebih berkelanjutan dan produktif. ",
            "category": "Budidaya & Pertanian",
        },
        {
            "id": 5,
            "title": "Terobosan Genetik: Varietas Tomat Unggul dengan Hasil Lebih Melimpah",
            "description": "Irigasi presisi dan teknologi modern bantu varian tomat unggul.",
            "url": "https://www.centrea.id/ecowatch/661156270/terobosan-inovasi-genetik-pengembangan-varietas-tomat-unggul-dengan-potensi-hasil-panen-yang-lebih-melimpah",
            "imageUrl": "https://cdn.pixabay.com/photo/2017/03/27/14/34/garden-2179095_1280.jpg",
            "publishedAt": "2025-04-05T09:45:00Z",
            "source": "Centrea",
            "content": "Revolusi pertanian tomat diwujudkan melalui inovasi genetik dan teknologi modern seperti irigasi tetes presisi, sensor tanah/cuaca real-time, rumah kaca dengan pengendalian iklim, serta drone dan robotika. Teknologi ini memungkinkan petani mengontrol air, nutrisi, dan lingkungan tumbuh secara optimal, meningkatkan produktivitas serta efisiensi penggunaan sumber daya. Platform digital dan analisis data turut membantu prediksi panen dan manajemen rantai pasok. Semua ini mendorong keberlanjutan dan kualitas hasil panen tomat dunia pertanian modern. ",
            "category": "Teknologi & Inovasi",
        },
        {
            "id": 6,
            "title": "Tomat Turun, 8 Ribu Rupiah Per Kilogram",
            "description": "Harga tomat turun drastis karena stok melimpah dan turunnya pembelian dari luar daerah.",
            "url": "https://rri.co.id/daerah/1804089/tomat-turun-8-ribu-rupiah-per-kilogram",
            "imageUrl": "https://cdn.pixabay.com/photo/2014/08/14/19/06/tomatoes-418203_1280.jpg",
            "publishedAt": "2025-08-30T00:00:00Z",
            "source": "RRI",
            "content": "Menurut pedagang, menurunnya harga tomat karena stok yang melimpah dan pembelian tomat dari luar daerah seperti Manado juga ikut turun sehingga harga turun drastis sekitar Rp8.000 per kilogram. ",
            "category": "Pasar & Harga",
        },
        {
            "id": 7,
            "title": "Harga Tomat di Pasar Melonguane Terus Turun",
            "description": "Tomat di Pasar Melonguane turun dari Rp10.000 menjadi Rp8.000 per kg.",
            "url": "https://rri.co.id/daerah/1806935/harga-tomat-di-pasar-melonguane-terus-turun",
            "imageUrl": "https://cdn.pixabay.com/photo/2016/09/03/23/34/cashbox-1642989_1280.jpg",
            "publishedAt": "2025-08-31T00:00:00Z",
            "source": "RRI",
            "content": "Di Pasar Melonguane, harga tomat turun dari Rp10.000 per kilogram menjadi sekitar Rp8.000 per kilogram, demikian disampaikan seorang pedagang bernama Rangga. ",
            "category": "Pasar & Harga",
        },
        {
            "id": 8,
            "title": "Inovasi Mahasiswa ITB Tawarkan Solusi Ramah Lingkungan untuk Kendali Hama Tomat",
            "description": "Mahasiswa ITB kembangkan teknik push-pull alami untuk kendalikan lalat buah pada tomat.",
            "url": "https://trubus.id/inovasi-mahasiswa-itb-tawarkan-solusi-ramah-lingkungan-untuk-kendali-hama-tomat/",
            "imageUrl": "https://cdn.pixabay.com/photo/2016/08/09/17/36/tomatoes-1581204_1280.jpg",
            "publishedAt": "2025-06-08T00:00:00Z",
            "source": "Trubus",
            "content": "Mahasiswa Institut Teknologi Bandung (ITB) merancang inovasi pengendalian hama lalat buah pada tanaman tomat menggunakan pendekatan ramah lingkungan berbasis teknik push-pull: mengusir hama dari tanaman utama dengan zat alami dan menariknya ke tanaman umpan atau perangkap. Teknik ini murah, mudah diterapkan, dan mengurangi ketergantungan terhadap pestisida kimia. Tim berencana melakukan uji coba lapangan dan menjalin kerja sama dengan petani serta lembaga pertanian untuk mengujinya lebih luas. ",
            "category": "Inovasi & Teknologi",
        },
        {
            "id": 9,
            "title": "Tomat Tanpa Biji, Inovasi Baru dalam Budidaya Pertanian",
            "description": "Peneliti Unpad kembangkan tomat partenokarpi yang tahan terhadap suhu tinggi.",
            "url": "https://radarlambar.bacakoran.co/read/22073/tomat-tanpa-biji-inovasi-baru-dalam-budidaya-pertanian",
            "imageUrl": "https://cdn.pixabay.com/photo/2015/10/21/10/07/tomato-999110_1280.jpg",
            "publishedAt": "2025-02-23T00:00:00Z",
            "source": "Radar Lambar",
            "content": "Syariful Mubarok dari Universitas Padjadjaran mengembangkan varietas tomat partenokarpi—buah tomat yang tumbuh tanpa melalui proses penyerbukan dan tidak memiliki biji. Varietas ini berpotensi berbuah di lingkungan tropis bersuhu tinggi hingga 45 °C. Amannya, tumbuh meski kondisi kurang mendukung. Mutasi gen IAA9 meningkatkan aktivitas hormon auksin yang memungkinkan pembentukan buah tanpa polinasi—inovasi menarik terhadap adaptasi iklim. ",
            "category": "Budidaya & Penelitian",
        },
        {
            "id": 10,
            "title": "Panen Perdana Tomat Ramah Lingkungan di Sulamadaha",
            "description": "Unkhair dan mitra lakukan panen perdana tomat ramah lingkungan dengan pupuk hayati.",
            "url": "https://unkhair.ac.id/kolaborasi-riset-unkhair-dan-pt-bio-konversi-panen-perdana-tanaman-tomat-ramah-lingkungan-di-sulamadaha/",
            "imageUrl": "https://cdn.pixabay.com/photo/2022/12/25/01/08/tomato-7676653_1280.jpg",
            "publishedAt": "2025-01-12T00:00:00Z",
            "source": "Universitas Khairun",
            "content": "Universitas Khairun bekerja sama dengan BRIN, Wahana Visi Indonesia, dan PT. Bio Konversi Indonesia melakukan panen perdana tanaman tomat ramah lingkungan di Sulamadaha, Ternate. Teknologi yang digunakan melibatkan pupuk hayati organik, dengan tujuan mengurangi ketergantungan pada pupuk kimia dan pestisida berbahaya. Diharapkan riset ini meningkatkan pendapatan petani lokal dan menyebarluaskan praktik pertanian berkelanjutan di Maluku Utara. ",
            "category": "Budidaya & Lingkungan",
        },
        {
            "id": 11,
            "title": "Cara Mengendalikan Penyakit Bercak Daun pada Tanaman Tomat",
            "description": "Penyakit bercak daun merupakan salah satu penyakit yang sering menyerang tanaman tomat. Penyakit ini disebabkan oleh jamur Cercospora capsici.",
            "url": "https://distan.bulelengkab.go.id/informasi/detail/artikel/cara-mengendalikan-penyakit-bercak-daun-pada-tanaman-tomat-89",
            "imageUrl": "https://cdn.pixabay.com/photo/2015/10/21/11/17/plant-999375_1280.jpg",
            "publishedAt": "2024-06-22T14:30:00Z",
            "source": "Dinas Pertanian Buleleng",
            "content": "Penyakit bercak daun merupakan salah satu penyakit yang sering menyerang tanaman tomat. Penyakit ini disebabkan oleh jamur Cercospora capsici. Gejala awal ditandai dengan adanya bercak kecil, bulat, berair pada daun. Bercak tersebut kemudian berkembang menjadi lebih besar, dengan diameter mencapai 0,5 cm, berwarna putih atau abu-abu di bagian tengahnya, dan dikelilingi oleh tepi berwarna coklat tua.\n\nSerangan berat dapat menyebabkan daun menguning, kering, dan akhirnya rontok sebelum waktunya. Kondisi ini tentu akan menghambat proses fotosintesis dan menurunkan produktivitas tanaman secara signifikan. Penyakit ini berkembang pesat pada suhu hangat (25-30°C) dan kelembaban udara yang tinggi.\n\nPengendalian dapat dilakukan dengan beberapa cara:\n1.  Kultur Teknis: Lakukan rotasi tanaman dengan tanaman yang bukan inang jamur. Jaga kebersihan kebun dan musnahkan sisa-sisa tanaman yang terinfeksi.\n2.  Pengendalian Hayati: Manfaatkan agens hayati seperti jamur Trichoderma sp. atau bakteri Pseudomonas fluorescens.\n3.  Pengendalian Kimiawi: Jika serangan sudah parah, gunakan fungisida dengan bahan aktif seperti mankozeb, klorotalonil, atau propineb. Lakukan penyemprotan sesuai dosis anjuran.",
            "category": "Hama & Penyakit",
        },
        {
            "id": 12,
            "title": "Mengenal Hama Kutu Kebul, Vektor Virus Keriting pada Tomat",
            "description": "Kutu kebul (Bemisia tabaci) sangat merugikan karena kemampuannya menjadi vektor virus kuning keriting yang berbahaya bagi tanaman tomat.",
            "url": "https://www.litbang.pertanian.go.id/info-teknologi/2943/",
            "imageUrl": "https://cdn.pixabay.com/photo/2023/01/07/07/33/tomato-7702780_1280.jpg",
            "publishedAt": "2024-05-10T09:00:00Z",
            "source": "Litbang Pertanian",
            "content": "Kutu kebul (Bemisia tabaci) adalah serangga kecil berwarna putih yang sering ditemukan bergerombol di bagian bawah daun. Meskipun ukurannya kecil, hama ini sangat berbahaya karena dua alasan utama: pertama, ia menghisap cairan tanaman yang menyebabkan daun menjadi keriput dan pertumbuhan terhambat. Kedua, dan yang paling merusak, kutu kebul adalah vektor utama penyebaran Tomato Yellow Leaf Curl Virus (TYLCV) atau Virus Keriting Daun Kuning.\n\nVirus ini tidak bisa disembuhkan dan menyebabkan kerugian panen total. Oleh karena itu, pengendalian kutu kebul adalah kunci utama. Beberapa metode pengendalian yang efektif meliputi:\n\n- **Fisik/Mekanis:** Memasang perangkap perekat kuning (yellow sticky traps) di sekitar tanaman untuk menarik dan menjebak kutu kebul dewasa.\n- **Kimiawi:** Menggunakan insektisida dengan bahan aktif seperti abamektin, tiametoksam, atau imidakloprid. Lakukan rotasi bahan aktif untuk mencegah resistensi hama.\n- Hayati: Memanfaatkan musuh alami seperti predator kumbang koksi atau parasitoid Encarsia formosa.",
            "category": "Hama & Penyakit",
        },
        {
            "id": 13,
            "title": "Teknik Budidaya Tomat Dataran Rendah Agar Panen Melimpah",
            "description": "Dengan teknik yang tepat, budidaya tomat di dataran rendah juga bisa menghasilkan panen yang optimal. Simak tips dan triknya di sini.",
            "url": "https://tabloidsinartani.com/detail/berita/0/gaya-hidup/19128/Teknik-Budidaya-Tomat-Dataran-Rendah-Agar-Panen-Melimpah",
            "imageUrl": "https://cdn.pixabay.com/photo/2015/09/21/20/58/tomatoes-950723_1280.jpg",
            "publishedAt": "2024-04-15T11:45:00Z",
            "source": "Tabloid Sinar Tani",
            "content": "Budidaya tomat di dataran rendah memiliki tantangan tersendiri, terutama suhu udara yang lebih tinggi dan kelembapan yang dapat memicu penyakit. Namun, dengan beberapa penyesuaian teknis, panen melimpah tetap bisa dicapai.\n\nBerikut adalah beberapa kunci suksesnya:\n\n1.  **Pemilihan Varietas:** Pilih varietas tomat yang toleran terhadap suhu panas. Beberapa varietas hibrida seperti Servo, Tymoti, atau Betavila dikenal memiliki adaptasi yang baik di dataran rendah.\n2.  **Pengaturan Waktu Tanam:** Hindari menanam di puncak musim hujan untuk mengurangi risiko serangan jamur. Awal atau akhir musim kemarau seringkali menjadi waktu yang lebih ideal.\n3.  **Irigasi yang Tepat:** Gunakan sistem irigasi tetes untuk menjaga kelembapan tanah tetap stabil tanpa membasahi daun, yang dapat mengurangi risiko penyakit daun.\n4.  **Sirkulasi Udara:** Berikan jarak tanam yang cukup (misalnya 60x70 cm) dan lakukan pemangkasan tunas air secara rutin untuk memastikan sirkulasi udara lancar di sekitar tanaman.",
            "category": "Budidaya",
        },
        {
            "id": 14,
            "title": "Pentingnya Pemupukan Berimbang pada Tanaman Tomat",
            "description": "Pemupukan berimbang adalah pemberian pupuk sesuai dengan kebutuhan tanaman dan kondisi lahan untuk meningkatkan produksi dan menjaga kesuburan tanah.",
            "url": "https://cybex.pertanian.go.id/artikel/99243/pemupukan-berimbang-pada-tanaman-tomat/",
            "imageUrl": "https://cdn.pixabay.com/photo/2020/03/18/08/58/tomato-4943313_1280.jpg",
            "content": "Pemupukan berimbang adalah kunci untuk mendapatkan tanaman tomat yang sehat dan produktif. Ini berarti memberikan unsur hara makro (N, P, K) dan mikro dalam jumlah yang tepat dan pada waktu yang tepat.\n\n- **Nitrogen (N):** Penting untuk pertumbuhan vegetatif, yaitu daun dan batang. Diberikan lebih banyak pada fase awal pertumbuhan.\n- **Fosfor (P):** Merangsang pertumbuhan akar, pembungaan, dan pembuahan. Sangat krusial saat tanaman mulai berbunga.\n- **Kalium (K):** Berperan penting dalam kualitas buah, seperti rasa, warna, ukuran, dan daya simpan. Dibutuhkan dalam jumlah besar saat fase pengisian buah.\n\nSebagai panduan umum, gunakan pupuk NPK dengan rasio seimbang seperti 16-16-16 pada fase awal. Saat tanaman memasuki fase generatif (berbunga dan berbuah), ganti ke pupuk dengan kandungan P dan K yang lebih tinggi, seperti pupuk MKP atau NPK grower.",
            "publishedAt": "2024-03-29T08:00:00Z",
            "source": "Cybex Pertanian",
            "category": "Budidaya",
        },
        {
            "id": 15,
            "title": "Cara Mengatasi Serangan Virus Gemini (Kuning) pada Tomat",
            "description": "Virus gemini menjadi momok bagi petani cabai dan tomat. Pengendaliannya harus fokus pada serangga vektornya, yaitu kutu kebul.",
            "url": "https://kabartani.com/cara-mengatasi-serangan-virus-gemini-pada-tanaman-cabai-dan-tomat.html",
            "imageUrl": "https://cdn.pixabay.com/photo/2019/05/09/03/07/tomato-4190313_1280.jpg",
            "content": "Virus Gemini, atau yang sering disebut penyakit kuning atau keriting, adalah salah satu penyakit paling merusak pada tomat. Penyakit ini disebabkan oleh Tomato Yellow Leaf Curl Virus (TYLCV).\n\nGejala khasnya adalah daun muda menjadi kerdil, menguning, melengkung ke atas (keriting seperti mangkok), dan kaku. Pertumbuhan tanaman akan terhenti dan tidak mampu menghasilkan buah. Hingga saat ini, belum ada obat yang bisa menyembuhkan tanaman yang sudah terinfeksi.\n\nOleh karena itu, tindakan terbaik adalah pencegahan, yang berfokus pada pengendalian serangga vektornya, yaitu kutu kebul (Bemisia tabaci). Langkah-langkah pencegahan meliputi:\n- Penggunaan varietas tomat yang tahan virus.\n- Pemasangan screen net (kasa) di persemaian untuk mencegah kutu kebul masuk.\n- Pemasangan yellow sticky trap (perangkap perekat kuning).\n- Penyemprotan insektisida secara rutin untuk menekan populasi kutu kebul.",
            "publishedAt": "2024-02-11T16:20:00Z",
            "source": "Kabar Tani",
            "category": "Hama & Penyakit",
        },
        {
            "id": 16,
            "title": "Manfaat Mulsa Plastik untuk Budidaya Tanaman Tomat",
            "description": "Penggunaan mulsa plastik hitam perak dapat menekan pertumbuhan gulma, menjaga kelembaban tanah, dan mengurangi serangan hama.",
            "url": "https://paktanidigital.com/artikel/manfaat-mulsa-plastik-untuk-budidaya-tanaman-tomat/",
            "imageUrl": "https://cdn.pixabay.com/photo/2016/07/20/14/19/ripening-tomatoes-1530464_1280.jpg",
            "content": "Mulsa plastik hitam perak (MPHP) adalah teknologi sederhana yang memberikan banyak sekali keuntungan dalam budidaya tomat. Sisi hitam menghadap ke bawah, sementara sisi perak menghadap ke atas.\n\nManfaat utamanya antara lain:\n\n1.  **Menekan Gulma:** Sisi hitam mencegah sinar matahari mencapai tanah, sehingga gulma tidak dapat tumbuh.\n2.  **Menjaga Kelembaban Tanah:** Mengurangi penguapan air dari permukaan tanah, sehingga efisiensi penggunaan air meningkat.\n3.  **Mengusir Hama:** Warna perak memantulkan sinar matahari, yang tidak disukai oleh hama seperti kutu daun (aphids) dan thrips.\n4.  **Menjaga Suhu Tanah:** Menjaga suhu tanah tetap stabil, baik di siang maupun malam hari.\n5.  **Mencegah Penyakit:** Mengurangi percikan tanah ke daun saat hujan, yang dapat membawa spora jamur penyebab penyakit.\n6.  **Menjaga Buah Tetap Bersih:** Buah yang menyentuh mulsa akan lebih bersih dibandingkan yang menyentuh tanah langsung.",
            "publishedAt": "2024-01-20T13:00:00Z",
            "source": "Pak Tani Digital",
            "category": "Budidaya",
        },
        {
            "id": 17,
            "title": "Pengendalian Hama Lalat Buah yang Menyerang Tomat",
            "description": "Lalat buah merupakan hama utama yang menyebabkan buah menjadi busuk dan rontok. Pelajari cara pengendaliannya secara efektif.",
            "url": "https://distan.jogjaprov.go.id/pengendalian-hama-lalat-buah/",
            "imageUrl": "https://cdn.pixabay.com/photo/2017/06/14/00/53/ripening-2400671_1280.jpg",
            "content": "Lalat buah (Bactrocera sp.) adalah hama yang sangat merugikan karena menyerang langsung bagian yang paling berharga, yaitu buah. Lalat betina dewasa akan menyuntikkan telurnya ke dalam buah tomat yang masih muda. Telur kemudian menetas menjadi larva (belatung) yang akan memakan daging buah dari dalam, menyebabkan buah menjadi busuk, berair, dan akhirnya rontok sebelum panen.\n\nMetode pengendalian yang bisa diterapkan adalah:\n\n- **Pemasangan Perangkap:** Gunakan perangkap yang mengandung atraktan atau pemikat seperti metil eugenol atau petrogenol. Perangkap ini akan menarik lalat jantan sehingga tidak dapat membuahi lalat betina.\n- **Sanitasi Kebun:** Kumpulkan dan musnahkan semua buah yang sudah terserang dan rontok. Jangan membiarkannya membusuk di lahan karena akan menjadi sumber perkembangbiakan lalat buah.\n- **Pembungkusan Buah:** Untuk budidaya skala kecil atau untuk buah bernilai tinggi, pembungkusan buah dengan plastik atau kertas khusus bisa menjadi cara yang sangat efektif.",
            "publishedAt": "2023-12-18T10:15:00Z",
            "source": "DPKPP DIY",
            "category": "Hama & Penyakit",
        },
        {
            "id": 18,
            "title": "Cara Membuat Pestisida Nabati dari Bawang Putih",
            "description": "Pestisida nabati adalah alternatif ramah lingkungan untuk mengendalikan hama. Bawang putih efektif untuk mengusir hama seperti kutu daun.",
            "url": "https://dlh.semarangkota.go.id/cara-membuat-pestisida-nabati-dari-bawang-putih/",
            "imageUrl": "https://cdn.pixabay.com/photo/2014/11/02/10/31/green-waste-513609_1280.jpg",
            "content": "Pestisida nabati dari bawang putih adalah cara yang murah, mudah, dan ramah lingkungan untuk mengendalikan hama penghisap seperti kutu daun, thrips, dan tungau.\n\nBerikut cara sederhana untuk membuatnya:\n\n1.  **Bahan:** Siapkan 100 gram bawang putih, 1 liter air, dan sedikit sabun cuci piring (sebagai perekat).\n2.  **Proses:** Blender atau tumbuk halus bawang putih. Campurkan dengan 1 liter air dan aduk hingga rata. Diamkan campuran tersebut selama 24 jam di tempat yang tertutup.\n3.  **Aplikasi:** Saring campuran dengan kain halus. Tambahkan beberapa tetes sabun cuci piring ke dalam larutan hasil saringan, lalu masukkan ke dalam botol semprot.\n\nSemprotkan larutan ini ke seluruh bagian tanaman, terutama di bagian bawah daun, pada pagi atau sore hari. Ulangi aplikasi setiap 3-5 hari sekali atau setelah hujan.",
            "publishedAt": "2023-11-05T11:00:00Z",
            "source": "DLH Semarang",
            "category": "Budidaya",
        },
        {
            "id": 19,
            "title": "Pengendalian Penyakit Layu Fusarium pada Tomat",
            "description": "Layu fusarium adalah penyakit tular tanah yang sulit dikendalikan. Pencegahan adalah kunci utama, salah satunya dengan sanitasi lahan.",
            "url": "https://pertanian.pontianakkota.go.id/artikel/61-pengendalian-penyakit-layu-fusarium.html",
            "imageUrl": "https://cdn.pixabay.com/photo/2014/09/19/19/09/man-452904_1280.jpg",
            "content": "Penyakit layu Fusarium disebabkan oleh jamur tanah Fusarium oxysporum f.sp. lycopersici. Jamur ini menginfeksi tanaman melalui akar dan menyumbat jaringan pembuluh (xilem), sehingga transportasi air dan nutrisi terganggu. Akibatnya, tanaman menjadi layu seolah-olah kekurangan air.\n\nGejala khasnya adalah daun bagian bawah menguning (seringkali hanya pada satu sisi tanaman atau satu cabang), diikuti oleh kelayuan yang terjadi pada siang hari dan tampak segar kembali pada malam hari. Pada akhirnya, tanaman akan layu permanen dan mati.\n\nKarena sangat sulit diobati, fokus utama adalah pencegahan:\n- Gunakan varietas tomat yang tahan terhadap Fusarium.\n- Lakukan rotasi tanaman dengan tanaman yang bukan inang (misalnya jagung atau padi).\n- Jaga pH tanah tetap netral (sekitar 6.5-7.0) dengan pengapuran.\n- Gunakan agens hayati seperti Trichoderma yang dapat menekan pertumbuhan jamur patogen.",
            "publishedAt": "2023-10-21T09:30:00Z",
            "source": "Dinas Pertanian Pontianak",
            "category": "Hama & Penyakit",
        },
        {
            "id": 20,
            "title": "5 Tanda Tomat Siap Panen, Apa Saja?",
            "description": "Memanen tomat pada waktu yang tepat sangat penting untuk mendapatkan rasa dan kualitas terbaik. Kenali tanda-tandanya.",
            "url": "https://www.kompas.com/homey/read/2023/08/14/192700876/5-tanda-tomat-siap-panen-apa-saja-",
            "imageUrl": "https://cdn.pixabay.com/photo/2013/03/01/19/36/cherry-tomatoes-88403_1280.jpg",
            "content": "Memanen tomat pada waktu yang tepat akan memaksimalkan rasa, nutrisi, dan daya simpan buah. Berikut adalah 5 tanda utama bahwa tomat Anda sudah siap dipetik:\n\n1.  **Warna Merata:** Sebagian besar permukaan buah sudah berubah warna secara merata sesuai dengan jenisnya (misalnya merah, kuning, atau oranye). Jangan menunggu hingga 100% matang di pohon jika ingin disimpan lebih lama.\n2.  **Tekstur Buah:** Saat ditekan perlahan, buah terasa padat dan berisi, tetapi sedikit empuk. Jika terlalu keras, berarti masih mentah. Jika terlalu lembek, berarti sudah terlalu matang.\n3.  **Aroma Khas:** Buah tomat yang matang akan mengeluarkan aroma khas yang segar dan sedikit manis di dekat bagian tangkainya.\n4.  **Mudah Dipetik:** Tangkai buah akan mudah dilepaskan dari batang utama dengan sedikit putaran lembut.\n5.  **Ukuran Maksimal:** Buah telah mencapai ukuran maksimal sesuai dengan karakteristik varietasnya.",
            "publishedAt": "2023-08-14T19:27:00Z",
            "source": "Kompas.com",
            "category": "Budidaya",
        },
        {
            "id": 21,
            "title": "Budidaya Tomat Hidroponik, Peluang Usaha yang Menggiurkan",
            "description": "Bertanam tomat tanpa tanah? Hidroponik adalah jawabannya. Metode ini bisa menjadi solusi untuk lahan sempit di perkotaan.",
            "url": "https://www.pertanian.go.id/home/?show=news&act=view&id=5229",
            "imageUrl": "https://images.pexels.com/photos/4953088/pexels-photo-4953088.jpeg",
            "content": "Hidroponik adalah teknik budidaya tanaman dengan memanfaatkan air sebagai media tanam utama yang kaya akan nutrisi. Untuk tomat, sistem hidroponik seperti irigasi tetes (drip irrigation) atau kultur air dalam (deep water culture) sangat populer.\n\nKeuntungan budidaya tomat secara hidroponik:\n- **Hemat Lahan:** Sangat cocok untuk area perkotaan atau lahan terbatas.\n- **Pertumbuhan Lebih Cepat:** Tanaman mendapatkan nutrisi yang dibutuhkan secara langsung dan terus-menerus.\n- **Kualitas Terkontrol:** Kualitas buah bisa lebih seragam karena nutrisi dan lingkungan terkontrol.\n- **Lebih Bersih:** Mengurangi risiko penyakit tular tanah dan buah yang dihasilkan lebih bersih.\n\nTantangannya meliputi biaya investasi awal untuk instalasi dan kebutuhan listrik untuk pompa air. Namun, dengan potensi hasil panen yang tinggi, hidroponik tomat menjadi peluang usaha yang menarik.",
            "publishedAt": "2023-07-02T12:00:00Z",
            "source": "Kementerian Pertanian RI",
            "category": "Budidaya",
        },
        {
            "id": 22,
            "title": "Pengendalian Penyakit Layu Bakteri pada Tanaman Tomat",
            "description": "Penyakit layu bakteri disebabkan oleh Ralstonia solanacearum dan menyebar dengan cepat. Pelajari cara mengidentifikasi dan mengendalikannya.",
            "url": "https://cybex.pertanian.go.id/artikel/98501/pengendalian-penyakit-layu-bakteri-ralstonia-solanacearum-pada-tanaman-tomat/",
            "imageUrl": "https://images.pexels.com/photos/4953088/pexels-photo-4953088.jpeg",
            "content": "Layu bakteri adalah salah satu penyakit paling ditakuti oleh petani tomat karena dapat menyebabkan kematian tanaman dalam waktu sangat singkat. Penyakit ini disebabkan oleh bakteri tular tanah Ralstonia solanacearum.\n\nGejala utamanya adalah kelayuan yang sangat cepat pada seluruh bagian tanaman tanpa didahului gejala menguning pada daun. Tanaman tampak sehat di pagi hari, layu di siang hari, dan bisa mati dalam beberapa hari. Ciri khas untuk membedakannya dari layu fusarium adalah jika potongan batang yang terinfeksi dimasukkan ke dalam gelas berisi air bening, akan keluar lendir putih seperti susu dari bekas potongan tersebut. Lendir ini adalah massa bakteri.\n\nPengendalian sangat sulit. Fokus utama adalah pencegahan:\n- Gunakan bibit yang sehat dan bebas penyakit.\n- Hindari menanam di lahan yang memiliki riwayat penyakit ini.\n- Lakukan rotasi tanaman dengan tanaman bukan inang seperti jagung.\n- Jaga drainase lahan agar tidak tergenang air.",
            "publishedAt": "2023-06-15T14:00:00Z",
            "source": "Cybex Pertanian",
            "category": "Hama & Penyakit",
        },
        {
            "id": 23,
            "title": "Mengenal Varietas Tomat Unggul Tahan Virus Gemini",
            "description": "Pemilihan varietas yang tahan penyakit adalah langkah awal yang krusial. Beberapa varietas tomat telah dirancang untuk tahan terhadap serangan virus gemini.",
            "url": "https://distanpangan.baliprov.go.id/mengenal-varietas-tomat-unggul-tahan-virus-gemini/",
            "imageUrl": "https://images.pexels.com/photos/9774996/pexels-photo-9774996.jpeg",
            "content": "Salah satu strategi paling efektif dan efisien untuk melawan penyakit Virus Kuning Keriting (Virus Gemini) adalah dengan menanam varietas yang sudah memiliki ketahanan genetik. Badan penelitian dan perusahaan benih terus berinovasi untuk menghasilkan varietas tomat hibrida yang tangguh.\n\nSaat memilih benih, perhatikan label pada kemasan. Biasanya akan tertera keterangan ketahanan terhadap penyakit. Cari kode seperti 'Tahan TYLCV' atau 'Toleran Virus Gemini'. Beberapa contoh varietas yang populer di kalangan petani karena ketahanannya antara lain Tymoti F1, Betavila F1, atau varietas lokal yang sudah teruji di daerah Anda.\n\nWalaupun varietas ini memiliki ketahanan, bukan berarti kebal 100%. Praktik budidaya yang baik seperti pengendalian vektor kutu kebul dan sanitasi lahan tetap harus dijalankan untuk menekan risiko serangan seminimal mungkin. Menggunakan varietas tahan adalah garda terdepan pertahanan Anda.",
            "publishedAt": "2023-05-30T10:45:00Z",
            "source": "Distan Pangan Bali",
            "category": "Budidaya",
        },
        {
            "id": 24,
            "title": "Penyebab Bunga Tomat Rontok dan Cara Mengatasinya",
            "description": "Bunga rontok adalah masalah umum yang menyebabkan gagal panen. Faktor cuaca ekstrem dan kekurangan nutrisi bisa menjadi penyebabnya.",
            "url": "https://mitalom.com/penyebab-bunga-tomat-rontok-dan-cara-mengatasinya/",
            "imageUrl": "https://images.pexels.com/photos/9774996/pexels-photo-9774996.jpeg",
            "content": "Kerontokan bunga pada tanaman tomat adalah masalah yang membuat frustrasi karena secara langsung berarti kegagalan pembentukan buah. Ada beberapa penyebab umum:\n\n1.  **Suhu Ekstrem:** Suhu yang terlalu panas (di atas 32°C) atau terlalu dingin (di bawah 13°C) dapat mengganggu proses penyerbukan dan menyebabkan bunga rontok.\n2.  **Stres Air:** Kekurangan atau kelebihan air dapat menyebabkan stres pada tanaman, yang memicu kerontokan bunga.\n3.  **Kekurangan Nutrisi:** Defisiensi unsur hara mikro seperti Boron (B) dan Kalsium (Ca) sangat berpengaruh pada kekuatan tangkai bunga dan proses pembuahan.\n4.  **Kurang Penyerbukan:** Kurangnya angin atau serangga penyerbuk dapat menyebabkan bunga tidak terbuahi dan akhirnya rontok.\n\nSolusinya adalah dengan menjaga penyiraman tetap konsisten, memberikan peneduh (naungan) jika cuaca terlalu panas, dan memastikan pemupukan yang seimbang, terutama pupuk yang mengandung unsur hara mikro.",
            "publishedAt": "2023-04-19T08:30:00Z",
            "source": "Mitalom.com",
            "category": "Budidaya",
        },
        {
            "id": 25,
            "title": "Manfaat dan Cara Pengapuran Lahan Pertanian",
            "description": "Tanah yang terlalu masam dapat menghambat penyerapan nutrisi oleh tanaman tomat. Pengapuran dengan dolomit adalah solusinya.",
            "url": "https://dinaspertanian.wonosobokab.go.id/manfaat-dan-cara-pengapuran-lahan-pertanian/",
            "imageUrl": "https://images.pexels.com/photos/14921002/pexels-photo-14921002.jpeg",
            "content": "Tingkat keasaman tanah (pH) adalah faktor kunci dalam kesuburan tanah. Sebagian besar lahan pertanian di Indonesia cenderung bersifat masam (pH rendah). Pada kondisi masam, unsur hara penting seperti Fosfor, Kalium, dan Magnesium menjadi terikat oleh tanah dan tidak tersedia bagi tanaman, meskipun Anda sudah memupuk.\n\nPengapuran adalah proses penambahan bahan kapur, seperti Kalsit (CaCO3) atau Dolomit (CaMg(CO3)2), ke dalam tanah untuk menaikkan pH-nya ke tingkat netral (sekitar 6.5).\n\nManfaat pengapuran:\n- Menaikkan pH tanah.\n- 'Membuka' ketersediaan unsur hara bagi tanaman.\n- Menambah unsur Kalsium (Ca) dan Magnesium (Mg) yang penting bagi tanaman.\n- Memperbaiki struktur tanah.\n\nPengapuran sebaiknya dilakukan 2-4 minggu sebelum proses penanaman, dengan cara disebar merata di permukaan tanah lalu dicampurkan saat pengolahan lahan.",
            "publishedAt": "2023-03-25T15:00:00Z",
            "source": "Dinas Pertanian Wonosobo",
            "category": "Budidaya",
        },
        {
            "id": 26,
            "title": "Cara Memangkas Tunas Air pada Tanaman Tomat agar Berbuah Lebat",
            "description": "Pemangkasan tunas air (wiwil) bertujuan untuk memfokuskan energi tanaman pada pembentukan buah, bukan pada pertumbuhan vegetatif yang berlebihan.",
            "url": "https://kumparan.com/seputar-hobi/cara-memangkas-tunas-air-pada-tanaman-tomat-agar-berbuah-lebat-21sXh5w02xH",
            "imageUrl": "https://images.pexels.com/photos/14921002/pexels-photo-14921002.jpeg",
            "content": "Pemangkasan atau 'wiwil' adalah teknik membuang tunas-tunas air yang tumbuh di ketiak daun (di antara batang utama dan cabang daun). Tunas ini, jika dibiarkan, akan tumbuh menjadi batang baru yang juga akan menghasilkan daun dan bunga, tetapi seringkali dengan kualitas buah yang lebih rendah. Tunas ini menyerap banyak energi dan nutrisi dari tanaman.\n\nDengan membuang tunas air, kita memfokuskan energi dan nutrisi tanaman untuk:\n- Memperbesar ukuran buah pada batang utama.\n- Mempercepat pematangan buah.\n- Meningkatkan kualitas rasa dan warna buah.\n- Melancarkan sirkulasi udara di sekitar tanaman, sehingga mengurangi risiko penyakit jamur.\n\nLakukan pemangkasan saat tunas masih kecil (panjang 2-5 cm) menggunakan jari atau gunting yang bersih. Wiwil sebaiknya dilakukan secara rutin, misalnya seminggu sekali.",
            "publishedAt": "2023-02-28T11:10:00Z",
            "source": "Kumparan",
            "category": "Budidaya",
        },
        {
            "id": 27,
            "title": "Hawar Daun Alternaria (Hawar Dini) pada Tomat",
            "description": "Penyakit ini biasanya menyerang daun tua terlebih dahulu dan ditandai dengan bercak konsentris seperti papan target. Pelajari siklus hidup dan pengendaliannya.",
            "url": "https://plantix.net/id/library/plant-diseases/100033/alternaria-blight/",
            "imageUrl": "https://images.pexels.com/photos/8180573/pexels-photo-8180573.jpeg",
            "content": "Hawar Daun Alternaria, atau sering disebut Hawar Dini (Early Blight), disebabkan oleh jamur Alternaria solani. Penyakit ini seringkali menjadi salah satu masalah utama dalam budidaya tomat, terutama di kondisi cuaca yang hangat dan lembab.\n\nGejala yang paling khas adalah munculnya bercak-bercak coklat tua pada daun, biasanya dimulai dari daun bagian bawah yang lebih tua. Bercak ini memiliki ciri khas berupa lingkaran-lingkaran konsentris di dalamnya, yang sering digambarkan seperti 'papan target'. Seiring perkembangan penyakit, bercak akan membesar dan daun akan menguning lalu mati.\n\nPengendaliannya meliputi:\n- Menjaga kebersihan kebun dari gulma dan sisa tanaman.\n- Memberikan jarak tanam yang cukup untuk sirkulasi udara.\n- Menghindari penyiraman dari atas yang membasahi daun.\n- Melakukan penyemprotan fungisida berbahan aktif mankozeb, klorotalonil, atau tembaga secara preventif.",
            "publishedAt": "2023-01-15T16:00:00Z",
            "source": "Plantix",
            "category": "Hama & Penyakit",
        },
        {
            "id": 28,
            "title": "Cara Membuat Pupuk Kompos dari Sampah Organik Rumah Tangga",
            "description": "Manfaatkan sampah dapur Anda untuk membuat pupuk kompos yang kaya nutrisi. Ini adalah cara mudah dan murah untuk menyuburkan tanaman tomat Anda.",
            "url": "https://lindungihutan.com/blog/cara-membuat-pupuk-kompos/",
            "imageUrl": "https://images.pexels.com/photos/8911771/pexels-photo-8911771.jpeg",
            "content": "Pupuk kompos adalah hasil penguraian bahan-bahan organik oleh mikroorganisme. Membuat kompos sendiri adalah cara terbaik untuk mengurangi sampah rumah tangga sekaligus mendapatkan pupuk berkualitas secara gratis.\n\nBahan yang dibutuhkan dibagi menjadi dua kategori:\n1.  **Bahan Hijau (Sumber Nitrogen):** Sisa sayuran, potongan rumput, ampas kopi, kulit buah.\n2.  **Bahan Coklat (Sumber Karbon):** Daun kering, serbuk gergaji, kardus, kertas koran.\n\nCara membuatnya secara sederhana:\n- Siapkan wadah (komposter atau lubang di tanah).\n- Masukkan bahan hijau dan bahan coklat secara berlapis dengan perbandingan sekitar 1:2 (1 bagian hijau, 2 bagian coklat).\n- Jaga agar tumpukan tetap lembab seperti spons yang diperas, jangan terlalu basah atau kering.\n- Aduk tumpukan setiap 1-2 minggu sekali untuk memberikan oksigen bagi mikroorganisme.\n\nDalam waktu 1-3 bulan, kompos akan matang, ditandai dengan warnanya yang coklat kehitaman, berbau seperti tanah, dan suhunya sudah dingin.",
            "publishedAt": "2022-12-20T10:00:00Z",
            "source": "LindungiHutan",
            "category": "Budidaya",
        },
        {
            "id": 29,
            "title": "Jarak Tanam Tomat yang Ideal untuk Hasil Panen Melimpah",
            "description": "Mengatur jarak tanam yang tepat akan mempengaruhi sirkulasi udara, paparan sinar matahari, dan pada akhirnya, jumlah dan kualitas buah yang dihasilkan.",
            "url": "https://kampustani.com/jarak-tanam-tomat/",
            "imageUrl": "https://images.pexels.com/photos/8180573/pexels-photo-8180573.jpeg",
            "content": "Jarak tanam adalah salah satu faktor teknis budidaya yang sering disepelekan namun memiliki dampak besar pada pertumbuhan dan hasil panen tomat. Jarak tanam yang terlalu rapat akan menyebabkan beberapa masalah:\n\n- **Persaingan Nutrisi:** Tanaman akan berebut unsur hara, air, dan sinar matahari, sehingga pertumbuhan kerdil.\n- **Sirkulasi Udara Buruk:** Kelembaban di sekitar tanaman menjadi tinggi, menciptakan kondisi ideal bagi perkembangan penyakit jamur.\n- **Sulitnya Perawatan:** Proses penyemprotan, pemangkasan, dan panen menjadi lebih sulit dilakukan.\n\nJarak tanam yang ideal bergantung pada tipe pertumbuhan tomat:\n- **Tipe Determinate (Pendek/Kerdil):** Biasanya cukup dengan jarak 40-50 cm antar tanaman dan 60-70 cm antar baris.\n- **Tipe Indeterminate (Tinggi/Merambat):** Membutuhkan jarak yang lebih lebar, sekitar 60-70 cm antar tanaman dan 80-100 cm antar baris, karena pertumbuhannya yang terus meninggi.",
            "publishedAt": "2022-11-18T09:00:00Z",
            "source": "Kampus Tani",
            "category": "Budidaya",
        },
        {
            "id": 30,
            "title": "Cara Mengatasi Penyakit Busuk Buah pada Tomat",
            "description": "Busuk buah adalah penyakit yang sering menyerang tomat, terutama saat musim hujan. Pelajari cara pencegahan dan pengendaliannya.",
            "url": "https://www.pertanian.go.id/home/?show=news&act=view&id=5201",
            "imageUrl": "https://images.pexels.com/photos/14920999/pexels-photo-14920999.jpeg",
            "content": "Penyakit busuk buah pada tomat disebabkan oleh beberapa faktor, termasuk infeksi jamur seperti Phytophthora infestans atau Botrytis cinerea. Gejala awalnya adalah munculnya bercak-bercak basah pada buah yang kemudian membesar dan berubah menjadi busuk.\n\nPenyebab utama penyakit ini adalah kelembaban tinggi, terutama saat musim hujan. Oleh karena itu, pencegahan adalah langkah terbaik:\n- **Sirkulasi Udara Baik:** Pastikan jarak tanam cukup untuk sirkulasi udara yang baik.\n- **Pengairan yang Tepat:** Hindari penyiraman dari atas yang membasahi daun dan buah.\n- **Sanitasi Kebun:** Hapus buah-buah yang sudah terinfeksi untuk mencegah penyebaran.\n- **Fungisida:** Gunakan fungisida berbahan aktif seperti mankozeb atau klorotalonil secara preventif.",
            "publishedAt": "2022-10-05T08:00:00Z",
            "source": "Kementerian Pertanian RI",
            "category": "Hama & Penyakit",
        },
    ]
    # Menambahkan 'id' unik ke setiap artikel
    articles_with_id = []
    for index, item in enumerate(news_items, start=1):
        item["id"] = index
        articles_with_id.append(item)

    return articles_with_id
